id: 60fd5479732e475dbbd7254f178281c9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_730-Dh%C4%81ra%E1%B9%87%C4%AB_T%C4%81r%C4%81%E2%80%99s_Own_Promise-v2.bo.en
  language: bo
  author: ''
  volume: {}
